name = "TravelingSalesmanExact"
uuid = "737fac7d-4440-55ef-927e-002196e95561"
authors = ["Eric <5846501+ericphanson@users.noreply.github.com>"]
version = "0.3.2"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[compat]
julia = "1"
UnicodePlots = "1"
MathOptInterface = "0.8, 0.9"
JuMP = "0.19, 0.20"

[extras]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GLPK"]
